### ISSUE TITLE
直线生成加一个垂直斜率

### ISSUE THREAD

**Issue by Northern-OceanS** [NorthernOceanS/NormaConstructor#16]
在直线生成器上加一个垂直斜率选项，表示每个直线的Y轴方向的斜率，斜率由用户输入
斜率默认为0，即标准的平面上的生成直线
设计原理类似一个带斜率的板/楼梯
考虑到是用来做楼梯和高架辅道的，因此斜率一般都小于1

另外有一个地下隧道选项
地下隧道选项为每生成一个直线上方会进行夷平（填空气），夷平的高度由用户输入
在建隧道很有用

**Comment by dzx-dzx** [comment]
应该完成了？
