### ISSUE TITLE
加一个全局取新坐标的选项

### ISSUE THREAD

**Issue by Northern-OceanS** [NorthernOceanS/NormaConstructor#21]
在UI最左栏加一个按钮，功能是启用全局取新坐标而不是保留旧坐标，应用于所有生成器
这个功能添加以后原直线生成的取新坐标按钮可以移除了

**Comment by dzx-dzx** [comment]
不可能强制要求生成器获取坐标的行为。
不过，可以加个标准生成器获取全局属性而控制行为。
