### ISSUE TITLE
Compreesion method

### ISSUE THREAD

**Issue by dzx-dzx** [NorthernOceanS/NormaConstructor#31]
In the current practice, all blocks are independent from each other. This has simplified the implementation in the past, but at the cost of redundant information.
One compression method is to group the blocks based on their blocktypes. 
`
{
blockTypes:[{...},{...}],
coordinates:[{x:0,y:0,z:0,blockTypeIndex:0},...]
}
`

**Comment by callstackexceed** [comment]
close this issue because of #47 and <https://github.com/NorthernOceanS/norma-core/issues/1>
