### ISSUE TITLE
Let framework handle buildInstruction

### ISSUE THREAD

**Issue by dzx-dzx** [NorthernOceanS/NormaConstructor#32]
As generators are platform-independent, its buildInstructions shouldn't be handled by the platform.

**Comment by callstackexceed** [comment]
Because of separation of framework, the issue should be done both here and <https://github.com/NorthernOceanS/norma-core/issues/2>.

**Comment by callstackexceed** [comment]
close this issue because of #47 and <https://github.com/NorthernOceanS/norma-core/issues/2>
