### ISSUE TITLE
Separation of Framework

### ISSUE THREAD

**Issue by dzx-dzx** [NorthernOceanS/NormaConstructor#43]
- Framework will be uploaded as an independent github repository and npm package.
    - “norma-core”
- Create another repository managing a yeoman&gulp-based toolchain.
    - Basic featurs:
    1. Create the “plugin” folder and its subdirectory, inside which developers can start their projects.
    2. Deploy and maintain framework and platforms that developers can test, run & package.
    3. “Watch”: Automatically deploy plugins and, if possible, refresh the platform(realizable on jsrunner) on the fly.
    4. “Package”: Package plugins as distributable platform-specified extension.(Compare it to released executables.)

**Comment by callstackexceed** [comment]
Part of this issue is already done in #47

**Comment by callstackexceed** [comment]
#69 is now issue for toolchain, so this can be closed
